### ISSUE TITLE
Nameplates sometimes appear offset from the top of a player's head.

### ISSUE THREAD

**Issue by ronniedude** [taffyko/LCNameplateTweaks#1]
![20231201203358_1](https://github.com/taffyko/LCNameplateTweaks/assets/37117448/1cc50e3c-b0ba-45d7-a5fb-44f863d5498e)
 In this example the nameplate 'Mattwars' is offset towards the right of the player's model (green suit crouched on the railing).

**Comment by taffyko** [comment]
thanks for reporting, i'll release an update to fix this!
