### ISSUE TITLE
LC API Dependency

### ISSUE THREAD

**Issue by ThrowawayAccount01** [taffyko/LCNameplateTweaks#3]
Noticed latest update added LC API dependency, when it wasn't needed before. Is this intentional? Reason I ask is that enabling LC API automatically adds the [MODDED] tag in front of lobbies with no way of disabling it, and it gives people the impression that my server is heavily modded when all I use are client side QOL mods.

**Comment by taffyko** [comment]
my bad! i was once considering adding a dependency on LC_API and forgot to remove it from the `manifest.json`, so it's still listing as a dependency.
fixing this in 1.0.4!
