### ISSUE TITLE
Getting error with NameplateTweaks

### ISSUE THREAD

**Issue by ko0416** [taffyko/LCNameplateTweaks#6]
I mostly play with 10+ friends and I receive an error log when using NapplateTweaks 1.0.5. 
The game won't crash. Just want to let you know if you can find any 'bug' or try to optimize the mod. 
Thank you for making this mod.

[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
NameplateTweaks.Patches.PlayerUpdate (GameNetcodeStuff.PlayerControllerB __instance) (at <7a519d0eb83b49b0ae9df8173638ef89>:IL_0099)
(wrapper dynamic-method) GameNetcodeStuff.PlayerControllerB.DMD<GameNetcodeStuff.PlayerControllerB::Update>(GameNetcodeStuff.PlayerControllerB)

**Comment by Aurathic** [comment]
I receive the same error occasionally when attempting to join random (non-modded) lobbies. I am able to "successfully" join the server, but my screen is frozen like this:

![20240105213521_1](https://github.com/taffyko/LCNameplateTweaks/assets/39442291/7d780ffc-20e7-4c13-8174-762c7914e072)

The mouse cursor from the main menu screen is also visible (not shown in the screenshot for some reason). I can move the mouse cursor and hear audio from the ship, but cannot move around, interact with anything, or access the tab or pause menus -- the only way to exit is to force-close the game. 

Unfortunately, I accidentally overwrote the players.log file, but managed to capture the last few hundred lines: [errorlog_betternameplates.txt](https://github.com/taffyko/LCNameplateTweaks/files/13848126/errorlog_betternameplates.txt). I believe the key error is the same:
```
[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
NameplateTweaks.Patches.PlayerUpdate (GameNetcodeStuff.PlayerControllerB __instance) (at <7a519d0eb83b49b0ae9df8173638ef89>:0)
(wrapper dynamic-method) GameNetcodeStuff.PlayerControllerB.DMD<GameNetcodeStuff.PlayerControllerB::Update>(GameNetcodeStuff.PlayerControllerB)
```

**Comment by taffyko** [comment]
thanks for the report, releasing 1.0.6 to fix this!
